/* Old Africa Adventures — gallery content
   Auto-generated by tools/generate-gallery-data.js — re-run that script
   after adding/removing files in assets/gallery/ rather than hand-editing
   the entries below (it renumbers everything for you). Safe to hand-edit
   the file header/comments, or to delete a whole numbered entry yourself
   if you don't want to wait to re-run the script.

   To remove a photo/video: find its "// #<id>" comment below (the same
   number appears as a small badge on its tile on gallery.html), delete
   that whole { ... } block including the comment above it, and delete the
   original file from assets/gallery/ too if you don't want it kept at
   all. IDs will have a gap until you next re-run the generator — that's
   fine, they don't need to be contiguous.

   Structure: { "<Category>": [ { id, type: "image", src, thumb } | { id, type: "video", src } ] }
   gallery.html / js/gallery.js read this to build the grid + lightbox. */

const OAA_GALLERY = {
    "Safari": [
        // #1 — 184e7367-404f-44b3-9166-df17e751e0ac_0_watermark.jpeg
        {
            id: 1,
            type: "image",
            src: "assets/gallery/Safari/184e7367-404f-44b3-9166-df17e751e0ac_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/184e7367-404f-44b3-9166-df17e751e0ac_0_watermark.jpg"
        },
        // #2 — 20250618_111050.jpg
        {
            id: 2,
            type: "image",
            src: "assets/gallery/Safari/20250618_111050.jpg",
            thumb: "assets/gallery/thumbs/Safari/20250618_111050.jpg"
        },
        // #3 — 20250721_162845.jpg
        {
            id: 3,
            type: "image",
            src: "assets/gallery/Safari/20250721_162845.jpg",
            thumb: "assets/gallery/thumbs/Safari/20250721_162845.jpg"
        },
        // #4 — 20251123_132533.jpg
        {
            id: 4,
            type: "image",
            src: "assets/gallery/Safari/20251123_132533.jpg",
            thumb: "assets/gallery/thumbs/Safari/20251123_132533.jpg"
        },
        // #5 — 20251127_100500.jpg
        {
            id: 5,
            type: "image",
            src: "assets/gallery/Safari/20251127_100500.jpg",
            thumb: "assets/gallery/thumbs/Safari/20251127_100500.jpg"
        },
        // #6 — 20260202_102357.jpg
        {
            id: 6,
            type: "image",
            src: "assets/gallery/Safari/20260202_102357.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260202_102357.jpg"
        },
        // #7 — 20260202_102445.jpg
        {
            id: 7,
            type: "image",
            src: "assets/gallery/Safari/20260202_102445.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260202_102445.jpg"
        },
        // #8 — 20260202_102459.jpg
        {
            id: 8,
            type: "image",
            src: "assets/gallery/Safari/20260202_102459.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260202_102459.jpg"
        },
        // #9 — 20260202_134524.jpg
        {
            id: 9,
            type: "image",
            src: "assets/gallery/Safari/20260202_134524.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260202_134524.jpg"
        },
        // #10 — 20260222_155654.jpg
        {
            id: 10,
            type: "image",
            src: "assets/gallery/Safari/20260222_155654.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260222_155654.jpg"
        },
        // #11 — 20260226_095132.jpg
        {
            id: 11,
            type: "image",
            src: "assets/gallery/Safari/20260226_095132.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260226_095132.jpg"
        },
        // #12 — 20260410_184011.jpg
        {
            id: 12,
            type: "image",
            src: "assets/gallery/Safari/20260410_184011.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260410_184011.jpg"
        },
        // #13 — 20260525_081710.jpg
        {
            id: 13,
            type: "image",
            src: "assets/gallery/Safari/20260525_081710.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260525_081710.jpg"
        },
        // #14 — 20260525_081718.jpg
        {
            id: 14,
            type: "image",
            src: "assets/gallery/Safari/20260525_081718.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260525_081718.jpg"
        },
        // #15 — 20260621_093455.jpg
        {
            id: 15,
            type: "image",
            src: "assets/gallery/Safari/20260621_093455.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_093455.jpg"
        },
        // #16 — 20260621_093458.jpg
        {
            id: 16,
            type: "image",
            src: "assets/gallery/Safari/20260621_093458.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_093458.jpg"
        },
        // #17 — 20260621_093509.jpg
        {
            id: 17,
            type: "image",
            src: "assets/gallery/Safari/20260621_093509.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_093509.jpg"
        },
        // #18 — 20260621_093536.jpg
        {
            id: 18,
            type: "image",
            src: "assets/gallery/Safari/20260621_093536.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_093536.jpg"
        },
        // #19 — 20260621_095949.jpg
        {
            id: 19,
            type: "image",
            src: "assets/gallery/Safari/20260621_095949.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_095949.jpg"
        },
        // #20 — 20260621_095955.jpg
        {
            id: 20,
            type: "image",
            src: "assets/gallery/Safari/20260621_095955.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_095955.jpg"
        },
        // #21 — 20260621_100310.jpg
        {
            id: 21,
            type: "image",
            src: "assets/gallery/Safari/20260621_100310.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_100310.jpg"
        },
        // #22 — 20260621_100319.jpg
        {
            id: 22,
            type: "image",
            src: "assets/gallery/Safari/20260621_100319.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_100319.jpg"
        },
        // #23 — 20260621_101011.jpg
        {
            id: 23,
            type: "image",
            src: "assets/gallery/Safari/20260621_101011.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260621_101011.jpg"
        },
        // #24 — 20260623_151754.jpg
        {
            id: 24,
            type: "image",
            src: "assets/gallery/Safari/20260623_151754.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260623_151754.jpg"
        },
        // #25 — 20260623_151807.jpg
        {
            id: 25,
            type: "image",
            src: "assets/gallery/Safari/20260623_151807.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260623_151807.jpg"
        },
        // #26 — 20260711_184016.jpg
        {
            id: 26,
            type: "image",
            src: "assets/gallery/Safari/20260711_184016.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260711_184016.jpg"
        },
        // #27 — 20260717_202051.jpg
        {
            id: 27,
            type: "image",
            src: "assets/gallery/Safari/20260717_202051.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260717_202051.jpg"
        },
        // #28 — 20260807_072150.jpg
        {
            id: 28,
            type: "image",
            src: "assets/gallery/Safari/20260807_072150.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260807_072150.jpg"
        },
        // #29 — 20260807_081304.jpg
        {
            id: 29,
            type: "image",
            src: "assets/gallery/Safari/20260807_081304.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260807_081304.jpg"
        },
        // #30 — 20260807_081308.jpg
        {
            id: 30,
            type: "image",
            src: "assets/gallery/Safari/20260807_081308.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260807_081308.jpg"
        },
        // #31 — 20260807_081445.jpg
        {
            id: 31,
            type: "image",
            src: "assets/gallery/Safari/20260807_081445.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260807_081445.jpg"
        },
        // #32 — 20260810_063829.jpg
        {
            id: 32,
            type: "image",
            src: "assets/gallery/Safari/20260810_063829.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260810_063829.jpg"
        },
        // #33 — 20260810_063928.jpg
        {
            id: 33,
            type: "image",
            src: "assets/gallery/Safari/20260810_063928.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260810_063928.jpg"
        },
        // #34 — 20260810_063944.jpg
        {
            id: 34,
            type: "image",
            src: "assets/gallery/Safari/20260810_063944.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260810_063944.jpg"
        },
        // #35 — 20260810_063959.jpg
        {
            id: 35,
            type: "image",
            src: "assets/gallery/Safari/20260810_063959.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260810_063959.jpg"
        },
        // #36 — 20260810_070236.jpg
        {
            id: 36,
            type: "image",
            src: "assets/gallery/Safari/20260810_070236.jpg",
            thumb: "assets/gallery/thumbs/Safari/20260810_070236.jpg"
        },
        // #37 — 2efd1a66-8054-4752-9a68-3249fa3363d7_0_watermark.jpeg
        {
            id: 37,
            type: "image",
            src: "assets/gallery/Safari/2efd1a66-8054-4752-9a68-3249fa3363d7_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/2efd1a66-8054-4752-9a68-3249fa3363d7_0_watermark.jpg"
        },
        // #38 — 40b619a7-baf1-4f22-a68d-ee29b5693785_0_watermark.jpeg
        {
            id: 38,
            type: "image",
            src: "assets/gallery/Safari/40b619a7-baf1-4f22-a68d-ee29b5693785_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/40b619a7-baf1-4f22-a68d-ee29b5693785_0_watermark.jpg"
        },
        // #39 — 4413fa16-6e55-4f30-b716-2aae4a114b1f_0_watermark.jpeg
        {
            id: 39,
            type: "image",
            src: "assets/gallery/Safari/4413fa16-6e55-4f30-b716-2aae4a114b1f_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/4413fa16-6e55-4f30-b716-2aae4a114b1f_0_watermark.jpg"
        },
        // #40 — 48cfa7ad-428b-40f5-a38e-574bf4b8da74_0_watermark.jpeg
        {
            id: 40,
            type: "image",
            src: "assets/gallery/Safari/48cfa7ad-428b-40f5-a38e-574bf4b8da74_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/48cfa7ad-428b-40f5-a38e-574bf4b8da74_0_watermark.jpg"
        },
        // #41 — 55be3179-af34-4cda-b68b-9a36587c32ec_0_watermark.jpeg
        {
            id: 41,
            type: "image",
            src: "assets/gallery/Safari/55be3179-af34-4cda-b68b-9a36587c32ec_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/55be3179-af34-4cda-b68b-9a36587c32ec_0_watermark.jpg"
        },
        // #42 — 6c6ce7f4-90bb-4f82-a8c6-b2ade2570657_0_watermark.jpeg
        {
            id: 42,
            type: "image",
            src: "assets/gallery/Safari/6c6ce7f4-90bb-4f82-a8c6-b2ade2570657_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/6c6ce7f4-90bb-4f82-a8c6-b2ade2570657_0_watermark.jpg"
        },
        // #43 — 9dd325d4-4072-48f3-9c1f-6c94b15aa099_0_watermark.jpeg
        {
            id: 43,
            type: "image",
            src: "assets/gallery/Safari/9dd325d4-4072-48f3-9c1f-6c94b15aa099_0_watermark.jpeg",
            thumb: "assets/gallery/thumbs/Safari/9dd325d4-4072-48f3-9c1f-6c94b15aa099_0_watermark.jpg"
        },
        // #44 — FB_IMG_1296277946442301089.jpg
        {
            id: 44,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_1296277946442301089.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_1296277946442301089.jpg"
        },
        // #45 — FB_IMG_1507956301282123012.jpg
        {
            id: 45,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_1507956301282123012.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_1507956301282123012.jpg"
        },
        // #46 — FB_IMG_2250994131801392146.jpg
        {
            id: 46,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_2250994131801392146.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_2250994131801392146.jpg"
        },
        // #47 — FB_IMG_2451361577805581919.jpg
        {
            id: 47,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_2451361577805581919.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_2451361577805581919.jpg"
        },
        // #48 — FB_IMG_2483466026334139504.jpg
        {
            id: 48,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_2483466026334139504.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_2483466026334139504.jpg"
        },
        // #49 — FB_IMG_3226632815053240936.jpg
        {
            id: 49,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_3226632815053240936.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_3226632815053240936.jpg"
        },
        // #50 — FB_IMG_4752731603691772959.jpg
        {
            id: 50,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_4752731603691772959.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_4752731603691772959.jpg"
        },
        // #51 — FB_IMG_8217238498089171409.jpg
        {
            id: 51,
            type: "image",
            src: "assets/gallery/Safari/FB_IMG_8217238498089171409.jpg",
            thumb: "assets/gallery/thumbs/Safari/FB_IMG_8217238498089171409.jpg"
        },
        // #52 — IMG-20250628-WA0037.jpg
        {
            id: 52,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250628-WA0037.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250628-WA0037.jpg"
        },
        // #53 — IMG-20250628-WA0043.jpg
        {
            id: 53,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250628-WA0043.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250628-WA0043.jpg"
        },
        // #54 — IMG-20250711-WA0055.jpg
        {
            id: 54,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250711-WA0055.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250711-WA0055.jpg"
        },
        // #55 — IMG-20250711-WA0056.jpg
        {
            id: 55,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250711-WA0056.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250711-WA0056.jpg"
        },
        // #56 — IMG-20250926-WA0144.jpg
        {
            id: 56,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0144.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0144.jpg"
        },
        // #57 — IMG-20250926-WA0145.jpg
        {
            id: 57,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0145.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0145.jpg"
        },
        // #58 — IMG-20250926-WA0147.jpg
        {
            id: 58,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0147.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0147.jpg"
        },
        // #59 — IMG-20250926-WA0153.jpg
        {
            id: 59,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0153.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0153.jpg"
        },
        // #60 — IMG-20250926-WA0155.jpg
        {
            id: 60,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0155.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0155.jpg"
        },
        // #61 — IMG-20250926-WA0156.jpg
        {
            id: 61,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0156.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0156.jpg"
        },
        // #62 — IMG-20250926-WA0158.jpg
        {
            id: 62,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0158.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0158.jpg"
        },
        // #63 — IMG-20250926-WA0159.jpg
        {
            id: 63,
            type: "image",
            src: "assets/gallery/Safari/IMG-20250926-WA0159.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20250926-WA0159.jpg"
        },
        // #64 — IMG-20260306-WA0053.jpg
        {
            id: 64,
            type: "image",
            src: "assets/gallery/Safari/IMG-20260306-WA0053.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20260306-WA0053.jpg"
        },
        // #65 — IMG-20260405-WA0027.jpg
        {
            id: 65,
            type: "image",
            src: "assets/gallery/Safari/IMG-20260405-WA0027.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20260405-WA0027.jpg"
        },
        // #66 — IMG-20260411-WA0064.jpg
        {
            id: 66,
            type: "image",
            src: "assets/gallery/Safari/IMG-20260411-WA0064.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20260411-WA0064.jpg"
        },
        // #67 — IMG-20260520-WA0038.jpg
        {
            id: 67,
            type: "image",
            src: "assets/gallery/Safari/IMG-20260520-WA0038.jpg",
            thumb: "assets/gallery/thumbs/Safari/IMG-20260520-WA0038.jpg"
        },
        // #68 — Screenshot_20260718_201431_Gallery.jpg
        {
            id: 68,
            type: "image",
            src: "assets/gallery/Safari/Screenshot_20260718_201431_Gallery.jpg",
            thumb: "assets/gallery/thumbs/Safari/Screenshot_20260718_201431_Gallery.jpg"
        },
    ],
};
