/* Old Africa Adventures — populates gallery.html
   Reads js/gallery-data.js (auto-generated by tools/generate-gallery-data.js)
   and renders a filterable grid plus a click-to-enlarge lightbox with
   keyboard/arrow navigation. No build step or dependencies — everything
   here is plain DOM manipulation. */

function flattenGallery(gallery, activeCategory) {
  const categories = activeCategory === 'all' ? Object.keys(gallery) : [activeCategory];
  return categories.flatMap(cat => gallery[cat] || []);
}

// The little "#N" badge matches the "// #N" comment above this item's
// entry in js/gallery-data.js — so if you spot a photo here you don't
// want, you can find and delete its exact block by that number.
function galleryBadgeHtml(item) {
  return `<span class="gallery-tile-id">#${item.id}</span>`;
}

function galleryTileHtml(item, index) {
  if (item.type === 'video') {
    return `
      <div class="gallery-tile" data-index="${index}">
        <video src="${item.src}#t=0.5" preload="metadata" muted playsinline></video>
        <div class="gallery-tile-play" aria-hidden="true">
          <svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>
        </div>
        ${galleryBadgeHtml(item)}
      </div>`;
  }
  const thumbSrc = item.thumb || item.src;
  return `
    <div class="gallery-tile" data-index="${index}">
      <img src="${thumbSrc}" alt="Moment from an Old Africa Adventures trip" loading="lazy"
        onerror="this.onerror=null; this.src='${item.src}';">
      ${galleryBadgeHtml(item)}
    </div>`;
}

document.addEventListener('DOMContentLoaded', () => {
  if (typeof OAA_GALLERY === 'undefined') return;

  const gridEl = document.getElementById('galleryGrid');
  const emptyEl = document.getElementById('galleryEmpty');
  const filtersEl = document.getElementById('galleryFilters');
  const categories = Object.keys(OAA_GALLERY);

  let activeCategory = 'all';
  let currentItems = [];
  let currentIndex = 0;

  const lightbox = document.getElementById('lightbox');
  const lightboxMedia = document.getElementById('lightboxMedia');
  const lightboxCounter = document.getElementById('lightboxCounter');

  function renderGrid() {
    currentItems = flattenGallery(OAA_GALLERY, activeCategory);
    gridEl.innerHTML = currentItems.map(galleryTileHtml).join('');
    emptyEl.style.display = currentItems.length ? 'none' : '';

    gridEl.querySelectorAll('.gallery-tile').forEach(tile => {
      tile.addEventListener('click', () => {
        openLightbox(Number(tile.getAttribute('data-index')));
      });
    });
  }

  function buildFilters() {
    if (categories.length <= 1) return; // nothing to filter between yet
    filtersEl.style.display = '';
    filtersEl.innerHTML = `<button class="filter-pill active" data-filter="all">All Moments</button>` +
      categories.map(c => `<button class="filter-pill" data-filter="${c}">${c}</button>`).join('');

    filtersEl.querySelectorAll('.filter-pill').forEach(pill => {
      pill.addEventListener('click', () => {
        filtersEl.querySelectorAll('.filter-pill').forEach(p => p.classList.remove('active'));
        pill.classList.add('active');
        activeCategory = pill.getAttribute('data-filter');
        renderGrid();
      });
    });
  }

  function renderLightboxMedia() {
    const item = currentItems[currentIndex];
    lightboxMedia.innerHTML = item.type === 'video'
      ? `<video src="${item.src}" controls autoplay playsinline></video>`
      : `<img src="${item.src}" alt="Moment from an Old Africa Adventures trip">`;
    lightboxCounter.textContent = `#${item.id} · ${currentIndex + 1} / ${currentItems.length}`;
  }

  function openLightbox(index) {
    currentIndex = index;
    renderLightboxMedia();
    lightbox.hidden = false;
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    lightbox.hidden = true;
    lightboxMedia.innerHTML = ''; // stop any playing video
    document.body.style.overflow = '';
  }

  function showNext() {
    currentIndex = (currentIndex + 1) % currentItems.length;
    renderLightboxMedia();
  }

  function showPrev() {
    currentIndex = (currentIndex - 1 + currentItems.length) % currentItems.length;
    renderLightboxMedia();
  }

  document.getElementById('lightboxClose').addEventListener('click', closeLightbox);
  document.getElementById('lightboxNext').addEventListener('click', showNext);
  document.getElementById('lightboxPrev').addEventListener('click', showPrev);
  lightbox.addEventListener('click', (e) => {
    if (e.target === lightbox) closeLightbox(); // click on the backdrop, not the media
  });
  document.addEventListener('keydown', (e) => {
    if (lightbox.hidden) return;
    if (e.key === 'Escape') closeLightbox();
    if (e.key === 'ArrowRight') showNext();
    if (e.key === 'ArrowLeft') showPrev();
  });

  buildFilters();
  renderGrid();
});
